# Generated by Django 3.2.3 on 2021-05-30 17:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(blank=True, null=True)),
                ('buy_price', models.PositiveIntegerField(blank=True, null=True)),
                ('sale_price', models.PositiveIntegerField(blank=True, null=True)),
                ('discount', models.PositiveIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('unavailable', 'unavailable'), ('low', 'low'), ('medium', 'medium'), ('available', 'available')], max_length=11)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
            options={
                'ordering': ('-id',),
            },
        ),
    ]
