# Generated by Django 3.2.3 on 2021-05-30 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productstock',
            options={'ordering': ('-id',), 'verbose_name': 'Stock', 'verbose_name_plural': 'Stock'},
        ),
    ]
