# Generated by Django 3.2.3 on 2021-05-30 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_alter_productstock_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='productstock',
            name='reorder_level',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
