# Generated by Django 3.2.3 on 2021-05-30 17:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0004_barcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barcode',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='stock.productstock'),
        ),
    ]
