# Generated by Django 3.2.3 on 2021-05-30 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0005_alter_barcode_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productstock',
            name='status',
            field=models.CharField(blank=True, choices=[('unavailable', 'unavailable'), ('low', 'low'), ('medium', 'medium'), ('available', 'available')], max_length=11, null=True),
        ),
    ]
