# Generated by Django 3.2.3 on 2021-06-27 10:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('when', models.DateTimeField(default=datetime.datetime(2021, 7, 4, 3, 50, 34, 783905))),
            ],
        ),
    ]
