# Generated by Django 3.2.3 on 2021-06-23 13:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='when',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 30, 6, 20, 3, 225338)),
        ),
    ]
