# Generated by Django 3.2.3 on 2021-06-27 11:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_alter_event_when'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='when',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 4, 4, 4, 27, 823764)),
        ),
    ]
