# Generated by Django 3.2.3 on 2021-05-29 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0002_remove_supplier_city'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='supplier',
            options={'ordering': ('-id',)},
        ),
    ]
