# Generated by Django 3.2.3 on 2021-06-27 10:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('people', '0001_initial'),
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_total', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('discount', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('tax', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('grand_total', models.PositiveIntegerField(default=0, null=True)),
                ('payment', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('left_to_pay', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('status', models.CharField(blank=True, choices=[('pending', 'Pending'), ('decline', 'Decline'), ('approved', 'Approved'), ('processing', 'Processing'), ('complete', 'Complete'), ('bulk', 'Bulk')], max_length=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='people.client')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
                ('products', models.ManyToManyField(to='products.Product')),
            ],
            options={
                'ordering': ('-id',),
            },
        ),
    ]
