# Generated by Django 3.2.3 on 2021-06-12 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_sale_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='grand_total',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
