# Generated by Django 3.2.3 on 2021-06-18 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_auto_20210617_0541'),
        ('sales', '0003_sale_grand_total'),
    ]

    operations = [
    ]
