# Generated by Django 3.2.3 on 2021-06-18 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_merge_0002_auto_20210617_0541_0003_sale_grand_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='grand_total',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
    ]
