# Generated by Django 3.2.3 on 2021-05-28 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_profile_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='email',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
