# Generated by Django 3.2.3 on 2021-06-22 12:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        ('people', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.PositiveIntegerField(default=0, null=True)),
                ('sub_total', models.PositiveIntegerField(default=0, null=True)),
                ('discount', models.PositiveIntegerField(default=0, null=True)),
                ('tax', models.PositiveIntegerField(default=0, null=True)),
                ('grand_total', models.PositiveIntegerField(default=0, null=True)),
                ('payment', models.PositiveIntegerField(default=0, null=True)),
                ('left_to_pay', models.PositiveIntegerField(default=0, null=True)),
                ('status', models.CharField(blank=True, choices=[('pending', 'Pending'), ('approved', 'Approved')], max_length=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
                ('products', models.ManyToManyField(to='products.Product')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='people.supplier')),
            ],
            options={
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='ProductAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('buy_price', models.PositiveIntegerField(blank=True, null=True)),
                ('sale_price', models.PositiveIntegerField(blank=True, null=True)),
                ('reorder_level', models.IntegerField(blank=True, default=0, null=True)),
                ('status', models.CharField(blank=True, choices=[('unavailable', 'unavailable'), ('low', 'low'), ('medium', 'medium'), ('available', 'available')], max_length=11, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
                ('purchase', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='purchases.purchase')),
            ],
            options={
                'verbose_name_plural': 'ProductsAttributes',
                'ordering': ('-id',),
            },
        ),
    ]
