# Generated by Django 3.2.3 on 2021-05-30 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='left_to_pay',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
