# Generated by Django 3.2.3 on 2021-06-16 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0002_alter_productattribute_purchase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productattribute',
            name='quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
