# Generated by Django 3.2.3 on 2021-06-16 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0004_auto_20210616_1101'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productattribute',
            old_name='discount',
            new_name='total_amount',
        ),
    ]
