# Generated by Django 3.2.3 on 2021-06-16 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0005_rename_discount_productattribute_total_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productattribute',
            name='total_amount',
        ),
    ]
