# Generated by Django 3.2.3 on 2021-06-18 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0004_purchase_grand_total'),
        ('purchases', '0006_remove_productattribute_total_amount'),
    ]

    operations = [
    ]
